
name: Release
on:
  push:
    branches: [ main ]
    tags-ignore:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          java-package: jdk
          distribution: 'zulu'

      - name: Set up api-telematik
        run: |
          cd api/
          git config --global user.email "no_reply@sberg.net"
          git config --global user.name "Release Bot"
          git clone https://github.com/gematik/api-telematik.git

      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1

      - name: Build with Maven
        id: build_maven
        run: |
          mvn -B package --file pom.xml
          VERSION=$(mvn --non-recursive help:evaluate -Dexpression=project.version -q -DforceStdout | grep -v '\[.*')
          echo "::set-output name=version::$VERSION"

      - uses: mukunku/tag-exists-action@v1.1.0
        id: checkTag
        with:
          tag: OpenKIM-${{ steps.build_maven.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish new version
        if: steps.checkTag.outputs.exists == 'false'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: sberg-net/openkim
          # `repo, user, admin:repo_hook`.
          repo_token: ${{ secrets.ACCESS_TOKEN }}
          file: target/openkim-${{ steps.build_maven.outputs.version }}.jar
          tag: OpenKIM-${{ steps.build_maven.outputs.version }}
          overwrite: false
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
